//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace OdorExperiment
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ExperimentMetadata
    {
    
        private string _experimentId;
    
        private string _subjectId;
    
        private string _operator;
    
        private System.DateTimeOffset _sessionStart;
    
        private string _notes;
    
        public ExperimentMetadata()
        {
            _notes = "";
        }
    
        protected ExperimentMetadata(ExperimentMetadata other)
        {
            _experimentId = other._experimentId;
            _subjectId = other._subjectId;
            _operator = other._operator;
            _sessionStart = other._sessionStart;
            _notes = other._notes;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ExperimentId")]
        public string ExperimentId
        {
            get
            {
                return _experimentId;
            }
            set
            {
                _experimentId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="SubjectId")]
        public string SubjectId
        {
            get
            {
                return _subjectId;
            }
            set
            {
                _subjectId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Operator")]
        public string Operator
        {
            get
            {
                return _operator;
            }
            set
            {
                _operator = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="SessionStart")]
        public System.DateTimeOffset SessionStart
        {
            get
            {
                return _sessionStart;
            }
            set
            {
                _sessionStart = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlIgnoreAttribute()]
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SessionStart")]
        public string SessionStartXml
        {
            get
            {
                return _sessionStart.ToString("o");
            }
            set
            {
                _sessionStart = System.DateTimeOffset.Parse(value);
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Notes")]
        public string Notes
        {
            get
            {
                return _notes;
            }
            set
            {
                _notes = value;
            }
        }
    
        public System.IObservable<ExperimentMetadata> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ExperimentMetadata(this)));
        }
    
        public System.IObservable<ExperimentMetadata> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ExperimentMetadata(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ExperimentId = " + _experimentId + ", ");
            stringBuilder.Append("SubjectId = " + _subjectId + ", ");
            stringBuilder.Append("Operator = " + _operator + ", ");
            stringBuilder.Append("SessionStart = " + _sessionStart + ", ");
            stringBuilder.Append("Notes = " + _notes);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HardwareConfig
    {
    
        private string _olfactometer1Port;
    
        private string _olfactometer2Port;
    
        private string _olfactometer3Port;
    
        private string _whiteRabbitPort;
    
        public HardwareConfig()
        {
        }
    
        protected HardwareConfig(HardwareConfig other)
        {
            _olfactometer1Port = other._olfactometer1Port;
            _olfactometer2Port = other._olfactometer2Port;
            _olfactometer3Port = other._olfactometer3Port;
            _whiteRabbitPort = other._whiteRabbitPort;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Olfactometer1Port")]
        public string Olfactometer1Port
        {
            get
            {
                return _olfactometer1Port;
            }
            set
            {
                _olfactometer1Port = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Olfactometer2Port")]
        public string Olfactometer2Port
        {
            get
            {
                return _olfactometer2Port;
            }
            set
            {
                _olfactometer2Port = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Olfactometer3Port")]
        public string Olfactometer3Port
        {
            get
            {
                return _olfactometer3Port;
            }
            set
            {
                _olfactometer3Port = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="WhiteRabbitPort")]
        public string WhiteRabbitPort
        {
            get
            {
                return _whiteRabbitPort;
            }
            set
            {
                _whiteRabbitPort = value;
            }
        }
    
        public System.IObservable<HardwareConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HardwareConfig(this)));
        }
    
        public System.IObservable<HardwareConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HardwareConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Olfactometer1Port = " + _olfactometer1Port + ", ");
            stringBuilder.Append("Olfactometer2Port = " + _olfactometer2Port + ", ");
            stringBuilder.Append("Olfactometer3Port = " + _olfactometer3Port + ", ");
            stringBuilder.Append("WhiteRabbitPort = " + _whiteRabbitPort);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ControlConfig
    {
    
        private string _startFlow;
    
        private string _disableFlow;
    
        private string _startPps;
    
        private string _endPps;
    
        private string _startExperiment;
    
        public ControlConfig()
        {
        }
    
        protected ControlConfig(ControlConfig other)
        {
            _startFlow = other._startFlow;
            _disableFlow = other._disableFlow;
            _startPps = other._startPps;
            _endPps = other._endPps;
            _startExperiment = other._startExperiment;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="StartFlow")]
        public string StartFlow
        {
            get
            {
                return _startFlow;
            }
            set
            {
                _startFlow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="DisableFlow")]
        public string DisableFlow
        {
            get
            {
                return _disableFlow;
            }
            set
            {
                _disableFlow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="StartPps")]
        public string StartPps
        {
            get
            {
                return _startPps;
            }
            set
            {
                _startPps = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="EndPps")]
        public string EndPps
        {
            get
            {
                return _endPps;
            }
            set
            {
                _endPps = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="StartExperiment")]
        public string StartExperiment
        {
            get
            {
                return _startExperiment;
            }
            set
            {
                _startExperiment = value;
            }
        }
    
        public System.IObservable<ControlConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ControlConfig(this)));
        }
    
        public System.IObservable<ControlConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ControlConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("StartFlow = " + _startFlow + ", ");
            stringBuilder.Append("DisableFlow = " + _disableFlow + ", ");
            stringBuilder.Append("StartPps = " + _startPps + ", ");
            stringBuilder.Append("EndPps = " + _endPps + ", ");
            stringBuilder.Append("StartExperiment = " + _startExperiment);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ProtocolConfig
    {
    
        private string _stimulusFile;
    
        private int _trialCount;
    
        private double _chargeSeconds;
    
        private double _deliverySeconds;
    
        private double _flushSeconds;
    
        private double _rechargeSeconds;
    
        private double _flowAdjustmentSeconds;
    
        private double _timeBeforeOdorSeconds;
    
        private double _isiMinimumSeconds;
    
        private double _isiMaximumSeconds;
    
        private int _mainFlow;
    
        private int _controlFlow;
    
        private int _flushFlow;
    
        private int _d1C0Flow;
    
        private int _d1C1Flow;
    
        private int _d1C2Flow;
    
        private int _d1C3Flow;
    
        private int _d2C0Flow;
    
        private int _d2C1Flow;
    
        private int _d2C2Flow;
    
        private int _d2C3Flow;
    
        private int _d3C0Flow;
    
        private int _d3C1Flow;
    
        private int _d3C2Flow;
    
        private int _d3C3Flow;
    
        public ProtocolConfig()
        {
        }
    
        protected ProtocolConfig(ProtocolConfig other)
        {
            _stimulusFile = other._stimulusFile;
            _trialCount = other._trialCount;
            _chargeSeconds = other._chargeSeconds;
            _deliverySeconds = other._deliverySeconds;
            _flushSeconds = other._flushSeconds;
            _rechargeSeconds = other._rechargeSeconds;
            _flowAdjustmentSeconds = other._flowAdjustmentSeconds;
            _timeBeforeOdorSeconds = other._timeBeforeOdorSeconds;
            _isiMinimumSeconds = other._isiMinimumSeconds;
            _isiMaximumSeconds = other._isiMaximumSeconds;
            _mainFlow = other._mainFlow;
            _controlFlow = other._controlFlow;
            _flushFlow = other._flushFlow;
            _d1C0Flow = other._d1C0Flow;
            _d1C1Flow = other._d1C1Flow;
            _d1C2Flow = other._d1C2Flow;
            _d1C3Flow = other._d1C3Flow;
            _d2C0Flow = other._d2C0Flow;
            _d2C1Flow = other._d2C1Flow;
            _d2C2Flow = other._d2C2Flow;
            _d2C3Flow = other._d2C3Flow;
            _d3C0Flow = other._d3C0Flow;
            _d3C1Flow = other._d3C1Flow;
            _d3C2Flow = other._d3C2Flow;
            _d3C3Flow = other._d3C3Flow;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="StimulusFile")]
        public string StimulusFile
        {
            get
            {
                return _stimulusFile;
            }
            set
            {
                _stimulusFile = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="TrialCount")]
        public int TrialCount
        {
            get
            {
                return _trialCount;
            }
            set
            {
                _trialCount = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ChargeSeconds")]
        public double ChargeSeconds
        {
            get
            {
                return _chargeSeconds;
            }
            set
            {
                _chargeSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="DeliverySeconds")]
        public double DeliverySeconds
        {
            get
            {
                return _deliverySeconds;
            }
            set
            {
                _deliverySeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="FlushSeconds")]
        public double FlushSeconds
        {
            get
            {
                return _flushSeconds;
            }
            set
            {
                _flushSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="RechargeSeconds")]
        public double RechargeSeconds
        {
            get
            {
                return _rechargeSeconds;
            }
            set
            {
                _rechargeSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="FlowAdjustmentSeconds")]
        public double FlowAdjustmentSeconds
        {
            get
            {
                return _flowAdjustmentSeconds;
            }
            set
            {
                _flowAdjustmentSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="TimeBeforeOdorSeconds")]
        public double TimeBeforeOdorSeconds
        {
            get
            {
                return _timeBeforeOdorSeconds;
            }
            set
            {
                _timeBeforeOdorSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="IsiMinimumSeconds")]
        public double IsiMinimumSeconds
        {
            get
            {
                return _isiMinimumSeconds;
            }
            set
            {
                _isiMinimumSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="IsiMaximumSeconds")]
        public double IsiMaximumSeconds
        {
            get
            {
                return _isiMaximumSeconds;
            }
            set
            {
                _isiMaximumSeconds = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="MainFlow")]
        public int MainFlow
        {
            get
            {
                return _mainFlow;
            }
            set
            {
                _mainFlow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ControlFlow")]
        public int ControlFlow
        {
            get
            {
                return _controlFlow;
            }
            set
            {
                _controlFlow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="FlushFlow")]
        public int FlushFlow
        {
            get
            {
                return _flushFlow;
            }
            set
            {
                _flushFlow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D1C0Flow")]
        public int D1C0Flow
        {
            get
            {
                return _d1C0Flow;
            }
            set
            {
                _d1C0Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D1C1Flow")]
        public int D1C1Flow
        {
            get
            {
                return _d1C1Flow;
            }
            set
            {
                _d1C1Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D1C2Flow")]
        public int D1C2Flow
        {
            get
            {
                return _d1C2Flow;
            }
            set
            {
                _d1C2Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D1C3Flow")]
        public int D1C3Flow
        {
            get
            {
                return _d1C3Flow;
            }
            set
            {
                _d1C3Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D2C0Flow")]
        public int D2C0Flow
        {
            get
            {
                return _d2C0Flow;
            }
            set
            {
                _d2C0Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D2C1Flow")]
        public int D2C1Flow
        {
            get
            {
                return _d2C1Flow;
            }
            set
            {
                _d2C1Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D2C2Flow")]
        public int D2C2Flow
        {
            get
            {
                return _d2C2Flow;
            }
            set
            {
                _d2C2Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D2C3Flow")]
        public int D2C3Flow
        {
            get
            {
                return _d2C3Flow;
            }
            set
            {
                _d2C3Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D3C0Flow")]
        public int D3C0Flow
        {
            get
            {
                return _d3C0Flow;
            }
            set
            {
                _d3C0Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D3C1Flow")]
        public int D3C1Flow
        {
            get
            {
                return _d3C1Flow;
            }
            set
            {
                _d3C1Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D3C2Flow")]
        public int D3C2Flow
        {
            get
            {
                return _d3C2Flow;
            }
            set
            {
                _d3C2Flow = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="D3C3Flow")]
        public int D3C3Flow
        {
            get
            {
                return _d3C3Flow;
            }
            set
            {
                _d3C3Flow = value;
            }
        }
    
        public System.IObservable<ProtocolConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ProtocolConfig(this)));
        }
    
        public System.IObservable<ProtocolConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ProtocolConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("StimulusFile = " + _stimulusFile + ", ");
            stringBuilder.Append("TrialCount = " + _trialCount + ", ");
            stringBuilder.Append("ChargeSeconds = " + _chargeSeconds + ", ");
            stringBuilder.Append("DeliverySeconds = " + _deliverySeconds + ", ");
            stringBuilder.Append("FlushSeconds = " + _flushSeconds + ", ");
            stringBuilder.Append("RechargeSeconds = " + _rechargeSeconds + ", ");
            stringBuilder.Append("FlowAdjustmentSeconds = " + _flowAdjustmentSeconds + ", ");
            stringBuilder.Append("TimeBeforeOdorSeconds = " + _timeBeforeOdorSeconds + ", ");
            stringBuilder.Append("IsiMinimumSeconds = " + _isiMinimumSeconds + ", ");
            stringBuilder.Append("IsiMaximumSeconds = " + _isiMaximumSeconds + ", ");
            stringBuilder.Append("MainFlow = " + _mainFlow + ", ");
            stringBuilder.Append("ControlFlow = " + _controlFlow + ", ");
            stringBuilder.Append("FlushFlow = " + _flushFlow + ", ");
            stringBuilder.Append("D1C0Flow = " + _d1C0Flow + ", ");
            stringBuilder.Append("D1C1Flow = " + _d1C1Flow + ", ");
            stringBuilder.Append("D1C2Flow = " + _d1C2Flow + ", ");
            stringBuilder.Append("D1C3Flow = " + _d1C3Flow + ", ");
            stringBuilder.Append("D2C0Flow = " + _d2C0Flow + ", ");
            stringBuilder.Append("D2C1Flow = " + _d2C1Flow + ", ");
            stringBuilder.Append("D2C2Flow = " + _d2C2Flow + ", ");
            stringBuilder.Append("D2C3Flow = " + _d2C3Flow + ", ");
            stringBuilder.Append("D3C0Flow = " + _d3C0Flow + ", ");
            stringBuilder.Append("D3C1Flow = " + _d3C1Flow + ", ");
            stringBuilder.Append("D3C2Flow = " + _d3C2Flow + ", ");
            stringBuilder.Append("D3C3Flow = " + _d3C3Flow);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class OutputConfig
    {
    
        private string _dataDirectory;
    
        private string _webhook;
    
        public OutputConfig()
        {
            _webhook = "";
        }
    
        protected OutputConfig(OutputConfig other)
        {
            _dataDirectory = other._dataDirectory;
            _webhook = other._webhook;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="DataDirectory")]
        public string DataDirectory
        {
            get
            {
                return _dataDirectory;
            }
            set
            {
                _dataDirectory = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Webhook")]
        public string Webhook
        {
            get
            {
                return _webhook;
            }
            set
            {
                _webhook = value;
            }
        }
    
        public System.IObservable<OutputConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new OutputConfig(this)));
        }
    
        public System.IObservable<OutputConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new OutputConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("DataDirectory = " + _dataDirectory + ", ");
            stringBuilder.Append("Webhook = " + _webhook);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Metadata and runtime parameters for one odor-delivery experiment.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Metadata and runtime parameters for one odor-delivery experiment.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ExperimentConfig
    {
    
        private ExperimentMetadata _metadata;
    
        private HardwareConfig _hardware;
    
        private ControlConfig _controls;
    
        private ProtocolConfig _protocol;
    
        private OutputConfig _output;
    
        public ExperimentConfig()
        {
            _metadata = new ExperimentMetadata();
            _hardware = new HardwareConfig();
            _controls = new ControlConfig();
            _protocol = new ProtocolConfig();
            _output = new OutputConfig();
        }
    
        protected ExperimentConfig(ExperimentConfig other)
        {
            _metadata = other._metadata;
            _hardware = other._hardware;
            _controls = other._controls;
            _protocol = other._protocol;
            _output = other._output;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Metadata")]
        public ExperimentMetadata Metadata
        {
            get
            {
                return _metadata;
            }
            set
            {
                _metadata = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Hardware")]
        public HardwareConfig Hardware
        {
            get
            {
                return _hardware;
            }
            set
            {
                _hardware = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Controls")]
        public ControlConfig Controls
        {
            get
            {
                return _controls;
            }
            set
            {
                _controls = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Protocol")]
        public ProtocolConfig Protocol
        {
            get
            {
                return _protocol;
            }
            set
            {
                _protocol = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Output")]
        public OutputConfig Output
        {
            get
            {
                return _output;
            }
            set
            {
                _output = value;
            }
        }
    
        public System.IObservable<ExperimentConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ExperimentConfig(this)));
        }
    
        public System.IObservable<ExperimentConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ExperimentConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Metadata = " + _metadata + ", ");
            stringBuilder.Append("Hardware = " + _hardware + ", ");
            stringBuilder.Append("Controls = " + _controls + ", ");
            stringBuilder.Append("Protocol = " + _protocol + ", ");
            stringBuilder.Append("Output = " + _output);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<ExperimentMetadata> source)
        {
            return Process<ExperimentMetadata>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HardwareConfig> source)
        {
            return Process<HardwareConfig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ControlConfig> source)
        {
            return Process<ControlConfig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ProtocolConfig> source)
        {
            return Process<ProtocolConfig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<OutputConfig> source)
        {
            return Process<OutputConfig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ExperimentConfig> source)
        {
            return Process<ExperimentConfig>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ExperimentMetadata>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HardwareConfig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ControlConfig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ProtocolConfig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OutputConfig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ExperimentConfig>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<ExperimentConfig>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}