//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Task
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Parameters for the odor loop. These are used to generate the Bonsai workflow.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Parameters for the odor loop. These are used to generate the Bonsai workflow.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class OdorLoop
    {
    
        private double _checkValveDelay;
    
        private double _endValve0Delay;
    
        private double _isiUpperBound;
    
        private double _isiLowerBound;
    
        private double _timeBeforeOdor;
    
        private string _trialCsvPath;
    
        public OdorLoop()
        {
        }
    
        protected OdorLoop(OdorLoop other)
        {
            _checkValveDelay = other._checkValveDelay;
            _endValve0Delay = other._endValve0Delay;
            _isiUpperBound = other._isiUpperBound;
            _isiLowerBound = other._isiLowerBound;
            _timeBeforeOdor = other._timeBeforeOdor;
            _trialCsvPath = other._trialCsvPath;
        }
    
        /// <summary>
        /// Delay after the check valve is opened before the odor is delivered, in seconds.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="check_valve_delay")]
        [System.ComponentModel.DescriptionAttribute("Delay after the check valve is opened before the odor is delivered, in seconds.")]
        public double CheckValveDelay
        {
            get
            {
                return _checkValveDelay;
            }
            set
            {
                _checkValveDelay = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="end_valve0_delay")]
        public double EndValve0Delay
        {
            get
            {
                return _endValve0Delay;
            }
            set
            {
                _endValve0Delay = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="isi_upper_bound")]
        public double IsiUpperBound
        {
            get
            {
                return _isiUpperBound;
            }
            set
            {
                _isiUpperBound = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="isi_lower_bound")]
        public double IsiLowerBound
        {
            get
            {
                return _isiLowerBound;
            }
            set
            {
                _isiLowerBound = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="time_before_odor")]
        public double TimeBeforeOdor
        {
            get
            {
                return _timeBeforeOdor;
            }
            set
            {
                _timeBeforeOdor = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="trial_csv_path")]
        public string TrialCsvPath
        {
            get
            {
                return _trialCsvPath;
            }
            set
            {
                _trialCsvPath = value;
            }
        }
    
        public System.IObservable<OdorLoop> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new OdorLoop(this)));
        }
    
        public System.IObservable<OdorLoop> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new OdorLoop(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CheckValveDelay = " + _checkValveDelay + ", ");
            stringBuilder.Append("EndValve0Delay = " + _endValve0Delay + ", ");
            stringBuilder.Append("IsiUpperBound = " + _isiUpperBound + ", ");
            stringBuilder.Append("IsiLowerBound = " + _isiLowerBound + ", ");
            stringBuilder.Append("TimeBeforeOdor = " + _timeBeforeOdor + ", ");
            stringBuilder.Append("TrialCsvPath = " + _trialCsvPath);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class TaskHardware
    {
    
        private string _olfactometer1Port;
    
        private string _olfactometer2Port;
    
        private string _whiteRabbitPort;
    
        public TaskHardware()
        {
        }
    
        protected TaskHardware(TaskHardware other)
        {
            _olfactometer1Port = other._olfactometer1Port;
            _olfactometer2Port = other._olfactometer2Port;
            _whiteRabbitPort = other._whiteRabbitPort;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="olfactometer1_port")]
        public string Olfactometer1Port
        {
            get
            {
                return _olfactometer1Port;
            }
            set
            {
                _olfactometer1Port = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="olfactometer2_port")]
        public string Olfactometer2Port
        {
            get
            {
                return _olfactometer2Port;
            }
            set
            {
                _olfactometer2Port = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="white_rabbit_port")]
        public string WhiteRabbitPort
        {
            get
            {
                return _whiteRabbitPort;
            }
            set
            {
                _whiteRabbitPort = value;
            }
        }
    
        public System.IObservable<TaskHardware> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new TaskHardware(this)));
        }
    
        public System.IObservable<TaskHardware> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new TaskHardware(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Olfactometer1Port = " + _olfactometer1Port + ", ");
            stringBuilder.Append("Olfactometer2Port = " + _olfactometer2Port + ", ");
            stringBuilder.Append("WhiteRabbitPort = " + _whiteRabbitPort);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Trial
    {
    
        private string _parameters;
    
        private string _result;
    
        public Trial()
        {
        }
    
        protected Trial(Trial other)
        {
            _parameters = other._parameters;
            _result = other._result;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="parameters")]
        public string Parameters
        {
            get
            {
                return _parameters;
            }
            set
            {
                _parameters = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="result")]
        public string Result
        {
            get
            {
                return _result;
            }
            set
            {
                _result = value;
            }
        }
    
        public System.IObservable<Trial> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Trial(this)));
        }
    
        public System.IObservable<Trial> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Trial(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Parameters = " + _parameters + ", ");
            stringBuilder.Append("Result = " + _result);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Task
    {
    
        private string _name;
    
        private string _loggingPath;
    
        private TaskHardware _hardware;
    
        private OdorLoop _odorLoop;
    
        private System.Collections.Generic.List<Trial> _trials;
    
        public Task()
        {
            _hardware = new TaskHardware();
            _odorLoop = new OdorLoop();
            _trials = new System.Collections.Generic.List<Trial>();
        }
    
        protected Task(Task other)
        {
            _name = other._name;
            _loggingPath = other._loggingPath;
            _hardware = other._hardware;
            _odorLoop = other._odorLoop;
            _trials = other._trials;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="name")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="logging_path")]
        public string LoggingPath
        {
            get
            {
                return _loggingPath;
            }
            set
            {
                _loggingPath = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="hardware")]
        public TaskHardware Hardware
        {
            get
            {
                return _hardware;
            }
            set
            {
                _hardware = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_loop")]
        public OdorLoop OdorLoop
        {
            get
            {
                return _odorLoop;
            }
            set
            {
                _odorLoop = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="trials")]
        public System.Collections.Generic.List<Trial> Trials
        {
            get
            {
                return _trials;
            }
            set
            {
                _trials = value;
            }
        }
    
        public System.IObservable<Task> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Task(this)));
        }
    
        public System.IObservable<Task> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Task(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("LoggingPath = " + _loggingPath + ", ");
            stringBuilder.Append("Hardware = " + _hardware + ", ");
            stringBuilder.Append("OdorLoop = " + _odorLoop + ", ");
            stringBuilder.Append("Trials = " + _trials);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<OdorLoop> source)
        {
            return Process<OdorLoop>(source);
        }

        public System.IObservable<string> Process(System.IObservable<TaskHardware> source)
        {
            return Process<TaskHardware>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Trial> source)
        {
            return Process<Trial>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Task> source)
        {
            return Process<Task>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OdorLoop>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<TaskHardware>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Trial>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Task>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<Task>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}